/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SermoesRouteImport } from './routes/sermoes'
import { Route as OracaoRouteImport } from './routes/oracao'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as ContribuirRouteImport } from './routes/contribuir'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CelulasRouteImport } from './routes/celulas'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicApproveAdminRouteImport } from './routes/api/public/approve-admin'
import { Route as AuthenticatedAdminConteudoRouteImport } from './routes/_authenticated/admin.conteudo'

const SermoesRoute = SermoesRouteImport.update({
  id: '/sermoes',
  path: '/sermoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OracaoRoute = OracaoRouteImport.update({
  id: '/oracao',
  path: '/oracao',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuirRoute = ContribuirRouteImport.update({
  id: '/contribuir',
  path: '/contribuir',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CelulasRoute = CelulasRouteImport.update({
  id: '/celulas',
  path: '/celulas',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicApproveAdminRoute = ApiPublicApproveAdminRouteImport.update({
  id: '/api/public/approve-admin',
  path: '/api/public/approve-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminConteudoRoute =
  AuthenticatedAdminConteudoRouteImport.update({
    id: '/conteudo',
    path: '/conteudo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRoute
  '/celulas': typeof CelulasRoute
  '/contato': typeof ContatoRoute
  '/contribuir': typeof ContribuirRoute
  '/mais': typeof MaisRoute
  '/oracao': typeof OracaoRoute
  '/sermoes': typeof SermoesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/api/public/approve-admin': typeof ApiPublicApproveAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRoute
  '/celulas': typeof CelulasRoute
  '/contato': typeof ContatoRoute
  '/contribuir': typeof ContribuirRoute
  '/mais': typeof MaisRoute
  '/oracao': typeof OracaoRoute
  '/sermoes': typeof SermoesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/api/public/approve-admin': typeof ApiPublicApproveAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRoute
  '/celulas': typeof CelulasRoute
  '/contato': typeof ContatoRoute
  '/contribuir': typeof ContribuirRoute
  '/mais': typeof MaisRoute
  '/oracao': typeof OracaoRoute
  '/sermoes': typeof SermoesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/conteudo': typeof AuthenticatedAdminConteudoRoute
  '/api/public/approve-admin': typeof ApiPublicApproveAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/biblia'
    | '/celulas'
    | '/contato'
    | '/contribuir'
    | '/mais'
    | '/oracao'
    | '/sermoes'
    | '/admin'
    | '/admin/conteudo'
    | '/api/public/approve-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/biblia'
    | '/celulas'
    | '/contato'
    | '/contribuir'
    | '/mais'
    | '/oracao'
    | '/sermoes'
    | '/admin'
    | '/admin/conteudo'
    | '/api/public/approve-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/auth'
    | '/biblia'
    | '/celulas'
    | '/contato'
    | '/contribuir'
    | '/mais'
    | '/oracao'
    | '/sermoes'
    | '/_authenticated/admin'
    | '/_authenticated/admin/conteudo'
    | '/api/public/approve-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  BibliaRoute: typeof BibliaRoute
  CelulasRoute: typeof CelulasRoute
  ContatoRoute: typeof ContatoRoute
  ContribuirRoute: typeof ContribuirRoute
  MaisRoute: typeof MaisRoute
  OracaoRoute: typeof OracaoRoute
  SermoesRoute: typeof SermoesRoute
  ApiPublicApproveAdminRoute: typeof ApiPublicApproveAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sermoes': {
      id: '/sermoes'
      path: '/sermoes'
      fullPath: '/sermoes'
      preLoaderRoute: typeof SermoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracao': {
      id: '/oracao'
      path: '/oracao'
      fullPath: '/oracao'
      preLoaderRoute: typeof OracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuir': {
      id: '/contribuir'
      path: '/contribuir'
      fullPath: '/contribuir'
      preLoaderRoute: typeof ContribuirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celulas': {
      id: '/celulas'
      path: '/celulas'
      fullPath: '/celulas'
      preLoaderRoute: typeof CelulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/approve-admin': {
      id: '/api/public/approve-admin'
      path: '/api/public/approve-admin'
      fullPath: '/api/public/approve-admin'
      preLoaderRoute: typeof ApiPublicApproveAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/conteudo': {
      id: '/_authenticated/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AuthenticatedAdminConteudoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConteudoRoute: typeof AuthenticatedAdminConteudoRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConteudoRoute: AuthenticatedAdminConteudoRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  BibliaRoute: BibliaRoute,
  CelulasRoute: CelulasRoute,
  ContatoRoute: ContatoRoute,
  ContribuirRoute: ContribuirRoute,
  MaisRoute: MaisRoute,
  OracaoRoute: OracaoRoute,
  SermoesRoute: SermoesRoute,
  ApiPublicApproveAdminRoute: ApiPublicApproveAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
